### PR TITLE
typings -> types + add exports.types

### PR DESCRIPTION
**Pull request by benasher44**
Fixes package.json so modern/stricter TS resolution modes can find the types

### CODE REVIEW

**Comment by tricinel** [comment]
Hey @benasher44, what was the issue with the types? Can you give an example?

**Comment by tricinel** [comment]
Looking at [this](https://arethetypeswrong.github.io/?p=highlight-words%401.2.2), it seems the types might already be correct.

To be honest, this is super confusing to me. My only concern is not breaking something else. So give me some time to figure it out please :)

**Comment by benasher44** [comment]
Huh that's a good point. I'll open an issue. Based on the TS error, there's either a TS bug, a bug with that tool, or an update is need here. I'll figure it out and report back!

**Comment by tricinel** [comment]
When in doubt, I think others are smarter and I messed up. So I will check nevertheless :D

Thanks!

**Comment by benasher44** [comment]
My mistake! I see types were actually fixed and work in this case if I just upgrade from 1.2.1 to 1.2.2

**Comment by tricinel** [comment]
Ah, thanks @benasher44! Glad it worked out and thanks for replying here. It saved me a few hours of digging into it 👍

**Pull request closed without merging**
